<a href="https://colab.research.google.com/github/jkinshuk/LogHubCodeSnip/blob/Snippet/Numpy_practice.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np
import pandas as pd

In [2]:
x = [1 ,2 ,3 , 4]

y = np.array(x)
print(y)
print(type(y))



[1 2 3 4]
<class 'numpy.ndarray'>


In [3]:
l = []
for i in range(1 , 5):
  int_l = int(input("Enter the no : "))
  l.append(int_l)

print(l)


Enter the no : 12
Enter the no : 13
Enter the no : 14
Enter the no : 15
[12, 13, 14, 15]


In [5]:
arr1 = np.array([[1 ,2 , 3]  , [4 , 5, 6]])
print(arr1)

print(f"The dimension : {arr1.ndim}")


[[1 2 3]
 [4 5 6]]
The dimension : 2


In [12]:
j = np.array([[[1, 2, 3, 4, 5], [12, 13, 14, 15 , 16], [1, 2, 3, 4, 5], [23, 45 , 55 , 65 , 75]]])
print(j)
print(f"The dimension: {j.ndim}")


[[[ 1  2  3  4  5]
  [12 13 14 15 16]
  [ 1  2  3  4  5]
  [23 45 55 65 75]]]
The dimension: 3


In [14]:
nums = np.array([1 ,2 ,3 , 4] , ndmin = 10)
print(nums)
value = nums.ndim
print(f"The dimensions {value}")

[[[[[[[[[[1 2 3 4]]]]]]]]]]
The dimensions 10


In [17]:
arzero = np.zeros(4)
hui = np.zeros((3 , 4))

print(arzero)
print(arzero.ndim)
print(type(arzero))


print(hui)
print(hui.ndim)
print(type(hui))


[0. 0. 0. 0.]
1
<class 'numpy.ndarray'>
[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
2
<class 'numpy.ndarray'>


In [18]:
#ones

In [19]:
ar_one = np.ones(4)
print(ar_one)

[1. 1. 1. 1.]


In [20]:
c = np.empty(4)
print(c)
print(c.ndim)
print(type(c))


[1. 1. 1. 1.]
1
<class 'numpy.ndarray'>


In [24]:
array_rn = np.arange(4)
print(array_rn)
print(array_rn.ndim)
print(type(array_rn))

[0 1 2 3]
1
<class 'numpy.ndarray'>


In [28]:
ar_dimension = np.eye(3)
ar_dim = np.eye(3,5)

In [29]:
print(ar_dimension)
print(ar_dim)

[[1. 0. 0.]
 [0. 1. 0.]
 [0. 0. 1.]]
[[1. 0. 0. 0. 0.]
 [0. 1. 0. 0. 0.]
 [0. 0. 1. 0. 0.]]


In [30]:
print(ar_dimension.ndim)
print(ar_dim.ndim)
print(type(ar_dimension))
print(type(ar_dim))

2
2
<class 'numpy.ndarray'>
<class 'numpy.ndarray'>


In [32]:
arr_lin = np.linspace(0 , 90, num = 5)
print(arr_lin)


[ 0.  22.5 45.  67.5 90. ]


In [33]:
var = np.random.rand(4)
print(var)

[0.84735148 0.85930846 0.75382237 0.72332913]


In [34]:
print(type(var))

<class 'numpy.ndarray'>


In [35]:
hj = np.random.rand(56)
print(hj)

[0.8229511  0.60287453 0.66189103 0.66229622 0.88803657 0.48779908
 0.90977025 0.05969628 0.4368888  0.49146842 0.64998427 0.95932272
 0.94401651 0.15176482 0.15226947 0.52521982 0.29973745 0.98103303
 0.10811164 0.57138427 0.56046351 0.66728992 0.94202428 0.30381635
 0.52498435 0.12585135 0.246639   0.48260195 0.51557828 0.34328703
 0.00102792 0.37091946 0.45708833 0.14902645 0.70286507 0.86888427
 0.72262424 0.77807069 0.0029968  0.03324803 0.80647629 0.8962367
 0.22694102 0.772872   0.40578711 0.11060419 0.02197585 0.19717794
 0.08299727 0.71088711 0.31204042 0.82122453 0.55646155 0.52183774
 0.60456941 0.42397442]


In [36]:
dfdj = np.random.rand(124)
print(dfdj)

[0.54813956 0.53234553 0.87255959 0.64563911 0.69360004 0.43047035
 0.79247422 0.40872903 0.01238866 0.37273994 0.56204169 0.97970757
 0.51818468 0.90288141 0.26394177 0.11755197 0.24867236 0.37862761
 0.20560337 0.44897632 0.52586144 0.68969279 0.89052881 0.25184363
 0.55985363 0.44759668 0.47600123 0.41641682 0.20303581 0.13567666
 0.53798316 0.92319117 0.86049845 0.21315725 0.78387542 0.72338144
 0.80130217 0.23020027 0.90815659 0.93046281 0.69165953 0.38024097
 0.59284244 0.16914019 0.2146946  0.40763768 0.22465627 0.44446006
 0.75947771 0.52332605 0.30833823 0.99497766 0.07542547 0.32001631
 0.06608745 0.23396028 0.04780572 0.30581776 0.04617442 0.58200037
 0.38379419 0.16708123 0.57628605 0.58478069 0.75930384 0.52386815
 0.81211206 0.03205202 0.81168316 0.80704717 0.51021541 0.70821855
 0.28005143 0.96431301 0.57548408 0.75055935 0.05881674 0.38610101
 0.18382249 0.31750101 0.50988919 0.06962324 0.43917841 0.15836779
 0.98678726 0.10603045 0.25542674 0.98914247 0.72381651 0.4028

In [37]:
dfj = np.random.randn(12)
print(dfj)

[-0.60084783  0.82332132  0.47377389  0.44674729 -0.03702207 -0.4876546
 -0.76907908 -1.09053658  1.5479333  -0.82124767 -0.11380483  0.68727086]


In [38]:
dj = np.random.randn(24)
print(dj)

[-0.1199707  -1.01124033 -3.04520115 -1.10428305  0.83122393  0.65459365
 -0.12755932  0.85620713 -1.15101105  0.38453631 -0.02856894  0.0482749
 -0.48627731  0.42556844  0.04638343 -2.08257493 -0.93586649 -0.35348562
 -0.04403407 -0.07900762 -0.62997511  0.78493909  0.27123766 -0.09478955]


In [39]:
print(dj)

[-0.1199707  -1.01124033 -3.04520115 -1.10428305  0.83122393  0.65459365
 -0.12755932  0.85620713 -1.15101105  0.38453631 -0.02856894  0.0482749
 -0.48627731  0.42556844  0.04638343 -2.08257493 -0.93586649 -0.35348562
 -0.04403407 -0.07900762 -0.62997511  0.78493909  0.27123766 -0.09478955]


In [40]:

complex_matrix = np.array([[1 + 2j, 3 - 4j], [5j, 6]])

print("Complex Matrix:")
print(complex_matrix)
print(f"The dimension: {complex_matrix.ndim}")


Complex Matrix:
[[1.+2.j 3.-4.j]
 [0.+5.j 6.+0.j]]
The dimension: 2


In [42]:
x = np.array([ [1 ,2 ,3 ,4 , 5 , 6, 7 , 8] , [127382 , 354, 54 , 56556, 656 , 565 ,656,56 ] , [234 , 3545 , 6565 , 77464 , 3434353 , 353535  ,5454 , 43435]])
print(x)


[[      1       2       3       4       5       6       7       8]
 [ 127382     354      54   56556     656     565     656      56]
 [    234    3545    6565   77464 3434353  353535    5454   43435]]


In [43]:
sum_of_rowsElement = np.sum(x , axis = 0)
sum_of_colsElement = np.sum(x , axis = 1)


In [44]:
print(sum_of_rowsElement)
print(sum_of_colsElement)


[ 127617    3901    6622  134024 3435014  354106    6117   43499]
[     36  186279 3924585]


In [45]:
mean_value = np.mean(x)
STANDARD_DEVIATION = np.std(x)

In [46]:
print(mean_value)
print(STANDARD_DEVIATION)

171287.5
684440.7858870383


In [47]:
min_value = np.mean(x)
max_value = np.max(x)
print(min_value)
print(max_value)

171287.5
3434353


In [49]:
argmin_index = np.argmin(x)
argmax_index = np.argmax(x)
print(argmin_index)
print(argmax_index)

0
20


In [51]:
squared_arr = np.square(x)  # Square each element
sqrt_arr = np.sqrt(x)  # Square root of each element


In [54]:
print(sqrt_arr)

[[1.00000000e+00 1.41421356e+00 1.73205081e+00 2.00000000e+00
  2.23606798e+00 2.44948974e+00 2.64575131e+00 2.82842712e+00]
 [3.56906150e+02 1.88148877e+01 7.34846923e+00 2.37815054e+02
  2.56124969e+01 2.37697286e+01 2.56124969e+01 7.48331477e+00]
 [1.52970585e+01 5.95399026e+01 8.10246876e+01 2.78323553e+02
  1.85320074e+03 5.94588093e+02 7.38512018e+01 2.08410652e+02]]


In [53]:
xmin = np.mean(sqrt_arr)
xmax = np.max(sqrt_arr)
print(xmin)
print(xmax)

161.82935383362204
1853.2007446577395


In [55]:
# min and max value index code :
zargmin = np.argmin(sqrt_arr)
zargmax = np.argmax(sqrt_arr)
print(zargmin)
print(zargmin)





0
0


In [56]:
print(sqrt_arr)

[[1.00000000e+00 1.41421356e+00 1.73205081e+00 2.00000000e+00
  2.23606798e+00 2.44948974e+00 2.64575131e+00 2.82842712e+00]
 [3.56906150e+02 1.88148877e+01 7.34846923e+00 2.37815054e+02
  2.56124969e+01 2.37697286e+01 2.56124969e+01 7.48331477e+00]
 [1.52970585e+01 5.95399026e+01 8.10246876e+01 2.78323553e+02
  1.85320074e+03 5.94588093e+02 7.38512018e+01 2.08410652e+02]]


In [57]:
Standard_deviation = np.std(sqrt_arr)

In [59]:
print(Standard_deviation)

380.9183117648617
